---
# Create a pod and expose port 80
kind: Deployment
metadata:
  name: app
  annotations:
    kubernetes.io/change-cause: "First release app:1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: dvdrbn/opsschool-jenkins-test-01:latest
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 80
      nodePort: 30038
      protocol: TCP
